name: conda
channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - fastqc=0.11.8
  - multiqc=1.7
  - minimap2=2.17
  - samtools=1.9
  - picard=2.20.2
  - deeptools=3.3.0
  - idr=2.0.4.2
  - r-ggplot2=3.1.1
  - subread=1.6.4
  - bedtools=2.27.1

