DEFAULTBUILD: GRCh38

REFS:
  GRCh37: GRCh37.primary_assembly.genome.fa.gz
  GRCh38: GRCh38.primary_assembly.genome.fa.gz

# See this: https://deeptools.readthedocs.io/en/develop/content/feature/effectiveGenomeSize.html
# For 75bp reads, these are the given values
EGS:
  GRCh37: 2736124973
  GRCh38: 2747877777
