DEFAULTBUILD: GRCh38

REFS:
  GRCh37: GRCh37.primary_assembly.genome.fa.gz
  GRCh38: GRCh38.primary_assembly.genome.fa.gz

# See this: https://deeptools.readthedocs.io/en/develop/content/feature/effectiveGenomeSize.html
# For 50bp reads, these are the given values
EGS:
  GRCh37: 2685511504
  GRCh38: 2701495761
